CC = gcc
CFLAGS = -Wall -Wextra -Werror
SRC = ft_strlen.c \
	ft_atoi.c \
	ft_strncmp.c \
	ft_isadigit.c \
	ft_isalnum.c \
	ft_isalpha.c\
	ft_isascii.c \
	ft_isprint.c \
	ft_toupper.c \
	ft_strlcat.c \
	ft_strnstr.c \
	ft_bero.c
OBJ = $(SRC: .c=.o)
LIBRARY = libft.a

.PHONY: all clean fclean re

all: $(LIBRARY)

$(LIBRARY): 